# -*- coding: utf-8 -*-
"""03_basic_eda.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rbo_G3u6BoHBXnHDkAAHvNV-W1nU7HwG
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


df = pd.read_csv('processed_food_crisis_data.csv')

#Global Food Insecurity Rankings Bar Chart

all_avg_scores = df.groupby('country')['food_insecurity_score'].mean().sort_values(ascending=False).reset_index()
plt.figure(figsize=(10, 20))

custom_palette = sns.cubehelix_palette(n_colors=len(all_avg_scores), start=.5, rot=-.5, reverse=True)
sns.barplot(
    data=all_avg_scores,
    x='food_insecurity_score',
    y='country',
    palette=custom_palette
)

plt.title('Global Food Insecurity Rankings', fontweight='bold', fontsize=14, pad=15)
plt.xlabel('Average Food Insecurity Score', fontsize=12)
plt.ylabel('Country', fontsize=12)


plt.tight_layout()
plt.show()


#Global Product Crisis Map Bubble Chart

product_analysis = df.groupby('product').agg({
    'crisis_label': 'sum',
    'volatility_ratio_3': 'mean',
    'food_insecurity_score': 'mean'
}).reset_index()

top_20 = product_analysis.nlargest(20, 'crisis_label')

plt.figure(figsize=(14, 10))
sns.set_theme(style="whitegrid")


scatter = plt.scatter(
    x=top_20['volatility_ratio_3'],
    y=top_20['food_insecurity_score'],
    s=top_20['crisis_label'] * 15, # Balon boyutunu ayarla
    alpha=0.6,
    c=top_20['food_insecurity_score'],
    cmap='YlOrRd',
    edgecolors="grey",
    linewidth=2
)

for i, row in top_20.iterrows():
    plt.annotate(row['product'], (row['volatility_ratio_3'], row['food_insecurity_score']),
                 fontsize=9, fontweight='bold', ha='center', va='center', xytext=(0, 15), textcoords='offset points')


plt.title('Global Product Crisis Map', fontsize=18, fontweight='bold', pad=30)
plt.xlabel('Average Price Volatility Ratio')
plt.ylabel('Mean Food Insecurity Score')
plt.colorbar(scatter).set_label('Food Insecurity Intensity')
plt.show()


#The Relationship Between Price Changes and Crisis Box Plot

sns.set_theme(style="whitegrid")

plt.figure(figsize=(10, 7))

df['crisis_label_str'] = df['crisis_label'].astype(str)

sns.boxplot(
    data=df,
    x='crisis_label_str',
    y='pct_change_1m',
    hue='crisis_label_str',
    palette={'0': 'lightgreen', '1': 'salmon'},
    legend=False
)


plt.title('The Relationship Between Price Changes and Crisis',fontweight='bold', fontsize=14, pad=15)
plt.xlabel('Crisis Status', fontsize=12)
plt.ylabel('Monthly Price Change (%)', fontsize=12)


plt.ylim(-25, 40)
plt.grid(True, axis='y', linestyle=':', alpha=0.6)


plt.tight_layout()
plt.show()


#Correlation of Crisis Prediction Variables Heatmap

cols_to_corr = [
    'avg_price', 'volatility_ratio_3', 'volatility_ratio_6',
    'price_lag_1', 'price_lag_3', 'price_lag_6',
    'food_insecurity_score', 'crisis_label'
]

corr_matrix = df[cols_to_corr].corr()
plt.figure(figsize=(12, 10))

sns.heatmap(
    corr_matrix,
    annot=True,
    cmap=sns.color_palette("Blues", as_cmap=True)
)

plt.title('Correlation of Crisis Prediction Variables', fontweight='bold', fontsize=16, pad=20)
plt.tight_layout()
plt.show()


#Distribution of Crisis Labels Bar Chart

plt.figure(figsize=(8, 6))
ax = sns.countplot(x='crisis_label', data=df, palette='hls')


plt.title("Distribution of Crisis Labels", fontsize=14, fontweight='bold')
plt.xlabel('Crisis Label', fontsize=12)
plt.ylabel('Count', fontsize=12)

for p in ax.patches:
    ax.annotate(f'{int(p.get_height())}',
                (p.get_x() + p.get_width() / 2., p.get_height()),
                ha = 'center', va = 'center',
                xytext = (0, 9),
                textcoords = 'offset points',
                fontsize=11)

sns.despine()
plt.tight_layout()
plt.show()


#Annual Crisis Intensity Heatmap

pivot_all = df.groupby(['country', 'year'])['crisis_label'].mean().unstack()
pivot_no_gaps = pivot_all.dropna()
top_25_countries_data = pivot_no_gaps.assign(avg=pivot_no_gaps.mean(axis=1)) \
                                     .sort_values(by='avg', ascending=False) \
                                     .head(25) \
                                     .drop(columns='avg')

plt.figure(figsize=(14, 12))
sns.heatmap(
    top_25_countries_data,
    annot=True,
    cmap='YlOrRd',
    fmt=".2f",
    linewidths=.5,
    cbar_kws={'label': 'Crisis Intensity (0.0 - 1.0)'}
)

plt.title('Annual Crisis Intensity', fontsize=16, fontweight='bold', pad=20)
plt.xlabel('Year', fontsize=12)
plt.ylabel('Country', fontsize=12)
plt.tight_layout()
plt.show()